language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
  - py.test example/tests.py --cov=example
  - cd -
script: pytest
after_success:
  - coveralls
