# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-03 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmonitor',
            name='response_body',
            field=models.CharField(blank=True, help_text='Body of the response returned when querying an endpoint', max_length=10000, null=True),
        ),
    ]
